apiVersion: v1
kind: Namespace
metadata:
  name: capd-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capd-controller-manager
  namespace: capd-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-docker
      control-plane: controller-manager
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: infrastructure-docker
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        - --metrics-bind-addr=127.0.0.1:8080
        image: gcr.io/k8s-staging-cluster-api/capd-manager:v1.6.0
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: Socket
        name: docker-sock
---
apiVersion: v1
kind: Service
metadata:
  name: capd-controller-manager-metrics-service
  namespace: capd-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    cluster.x-k8s.io/provider: infrastructure-docker
    control-plane: controller-manager