apiVersion: v1
kind: Namespace
metadata:
  name: capd-system
---
# 1. Le ServiceAccount 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: capd-manager
  namespace: capd-system
---
# 2. Certificats pour le Webhook
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: capd-selfsigned-issuer
  namespace: capd-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capd-serving-cert
  namespace: capd-system
spec:
  dnsNames:
  - capd-webhook-service.capd-system.svc
  - capd-webhook-service.capd-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capd-selfsigned-issuer
  secretName: capd-webhook-service-cert
  subject:
    organizations:
    - k8s.io
---
# 3. Services (Metrics & Webhook)
apiVersion: v1
kind: Service
metadata:
  name: capd-controller-manager-metrics-service
  namespace: capd-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    cluster.x-k8s.io/provider: infrastructure-docker
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  name: capd-webhook-service
  namespace: capd-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    cluster.x-k8s.io/provider: infrastructure-docker
    control-plane: controller-manager
---
# 4. Le Deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capd-controller-manager
  namespace: capd-system
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-docker
      control-plane: controller-manager
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: infrastructure-docker
        control-plane: controller-manager
    spec:
      serviceAccountName: capd-manager # <--- IMPORTANT : Utilise le compte créé plus haut
      containers:
      - args:
        - --leader-elect
        - --metrics-bind-addr=127.0.0.1:8080
        - --webhook-port=9443
        - --webhook-cert-dir=/tmp/k8s-webhook-server/serving-certs/
        image: gcr.io/k8s-staging-cluster-api/capd-manager:v1.7.0
        name: manager
        securityContext:
          privileged: true
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: Socket
        name: docker-sock
      - name: cert
        secret:
          defaultMode: 420
          secretName: capd-webhook-service-cert
---
# 5. Droits RBAC : Leader Election (Role local)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capd-leader-election-role
  namespace: capd-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: capd-leader-election-rolebinding
  namespace: capd-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: capd-leader-election-role
subjects:
- kind: ServiceAccount
  name: capd-manager
  namespace: capd-system
---
# 6. Droits RBAC : Manager Global (ClusterRole)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capd-manager-role
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
rules:
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - dockerclusters
      - dockerclusters/status
      - dockermachines
      - dockermachines/status
      - dockermachinetemplates
      - dockermachinepools
      - dockermachinepools/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusters
      - clusters/status
      - machines
      - machines/status
      - machinepools
      - machinepools/status
      - machinesets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capd-manager-rolebinding
  labels:
    cluster.x-k8s.io/provider: infrastructure-docker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capd-manager-role
subjects:
  - kind: ServiceAccount
    name: capd-manager
    namespace: capd-system